# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang Formatter
on: [pull_request]
jobs:
  build:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Golang Formatter
      uses: sladyn98/auto-go-format@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
